  
---

AllCops:
  Exclude:
    - 'bin/**'
    - 'db/schema.rb'
    - 'db/migrate/**'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'db/seeds.rb'
  SuggestExtensions: false
  NewCops: enable

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - 'app/controllers/sessions_controller.rb'
